services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_bWF4aW11bS1ibHVlamF5LTM2LmNsZXJrLmFjY291bnRzLmRldiQ
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: /ideas
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: /ideas
        NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: /admin
        NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: /admin
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dahtqvzef
        NEXT_PUBLIC_CLOUDINARY_API_KEY: 367716776171696
        NEXT_PUBLIC_CLOUDINARY_API_SECRET: TFHLKuaUnkLT-o4C0La-QX91o8Y
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend