services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_bWF4aW11bS1ibHVlamF5LTM2LmNsZXJrLmFjY291bnRzLmRldiQ
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: /ideas
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: /ideas
        NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: /admin
        NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: /admin
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dq6n2ez9v
        NEXT_PUBLIC_CLOUDINARY_API_KEY: 697775542728211
        NEXT_PUBLIC_CLOUDINARY_API_SECRET: x5D3x4dhAMa8eZtCk64qBsKVIbA
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend